project:
  seed: 42

paths:
  processed_dir: null
  splits_dir: null

dataset:
  name: Teeth3DS
  split_source: teethseg22
  splits:
    - train
    - val
  expected_num_points: 60000
  num_classes: 17

segmentation_dataset:
  feature_keys:
    - pos
    - normal
  target_key: y_arch_class

dataloader:
  train:
    batch_size: 16
    num_workers: 4
    shuffle: true
  eval:
    batch_size: 16
    num_workers: 4
    shuffle: false
